### ISSUE TITLE
UnionPay expressPay card validation problem

### ISSUE THREAD

**Issue by jovpet** [nogorilla/angular-cc-library#40]
UnionPay ExpressPay card, (19 digits number) doesn't pass validation. A test card from Adyen 8171 9999 0000 0000 021, that can be found here: https://docs.adyen.com/developers/test-cards/test-card-numbers#unionpaysecureplusdebitcard doesn't validate.

**Comment by thekip** [comment]
This library uses Regexp to validate a card number against of list of predefined values. 
 Unfortunately, there are much more card schemes in real word than bundled in this library
 And it's just impossible to cover them all in this library (it will also blow up a bundle size significantly).

I see a solution for this issue is just allow users to add own type of cards, there is a feature request https://github.com/nogorilla/angular-cc-library/issues/46
